<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />

  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TrueCounsel.Application\TrueCounsel.Application.csproj" />
    <ProjectReference Include="..\TrueCounsel.Domain\TrueCounsel.Domain.csproj" />
  </ItemGroup>
</Project>