<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <Compile Remove="Controllers\V1\**" />
    <Content Remove="Controllers\V1\**" />
    <EmbeddedResource Remove="Controllers\V1\**" />
    <None Remove="Controllers\V1\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="WakaTime" />
   
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrueCounsel.Application\TrueCounsel.Application.csproj" />
    <ProjectReference Include="..\TrueCounsel.Infrastructure\TrueCounsel.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\" />
  </ItemGroup>

</Project>
